Feat: User inputs validation
DevdouglasGfs/taqtile pull request #10
Opened 2024-06-19 16:45 UTC by DevdouglasGfs

# User Inputs Validation

Don't allow the form submission with invalid user inputs

This solves the issue #7

2024-06-21 22:44 UTC, walteraandrade commented on src/components/login-form/index.tsx
> +                <p className='input-group__informative-message'>A senha deve ter ao menos 7 caractéres.</p>
```suggestion
                <p className='input-group__informative-message'>A senha deve ter ao menos 7 caracteres.</p>
```

2024-06-21 22:44 UTC, walteraandrade commented on src/components/login-form/index.tsx
> +                <p className='input-group__informative-message'>A senha deve ser composta por caractéres alfánumericos.</p>
```suggestion
                <p className='input-group__informative-message'>A senha deve ser composta por caracteres alfánumericos.</p>
```

2024-06-21 22:44 UTC, walteraandrade commented on src/components/login-form/index.tsx
> +              {validPassword ? 'true' : 'false'}
não entendi isso 🤔

2024-06-21 22:49 UTC, DevdouglasGfs commented on src/components/login-form/index.tsx
> +              {validPassword ? 'true' : 'false'}
Ah, quanto a isso foi um teste que fiz para vêr se estava se comportando de acordo 😁 apaguei na outra PR

2024-06-24 19:38 UTC, SamuelSsc requested changes
Esse pr está comparando com a branch errada como base, como consequência aparecem implementações que você fez em outro momento, ao abrir um pr ajusta na parte de cima para onde ele está apontando Ex esse de dev aqui abaixo: 
<img width="405" alt="image" src="https://github.com/DevdouglasGfs/taqtile/assets/60801255/adb1d96e-0f53-4469-bfef-2ffa380c789e">

No seu caso se você criou essa branch logo depois da de login você já abre ela apontando para de login, dessa forma só vai aparecer alterações dessa branch aqui especificamente.

2024-06-24 19:43 UTC, DevdouglasGfs commented
Ahhh, muito obrigado! Não sabia disso

2024-06-24 23:39 UTC, DevdouglasGfs commented
Pronto, fix o rebase necessário. Obrigado pelo auxílio novamente 💯

2024-06-26 09:04 UTC, DevdouglasGfs commented
Posso dar merge?

2024-06-26 15:28 UTC, DevdouglasGfs commented
Assim que é feita a validação nesta branch
![Screenshot_20240626-122342](https://github.com/DevdouglasGfs/taqtile/assets/105404079/d3b5124b-d74d-4a41-9cba-d5d917aa383f)
![Screenshot_20240626-122639](https://github.com/DevdouglasGfs/taqtile/assets/105404079/0f56506a-519d-4317-b3d6-1aa1b5ef68aa)

2024-06-26 20:36 UTC, SamuelSsc approved these changes

2024-06-27 16:51 UTC, closed without merging